### ISSUE TITLE
Jump Chains

### ISSUE THREAD

**Issue by ETang444** [ETang444/Jack-Aivant-Eric-CheckersAI#2]
After jumping a piece, a player can move again, but ONLY if they move the same piece that they just moved, and only if that piece can jump something else. Otherwise, their turn ends. Since CheckersOp is storing the turn information, and determining if a move is legal, it also needs to figure out these jumping rules.

This means we need a new helper method in the CheckersOp class: hasNextJump(int jumper). It means we also need a new global variable in the CheckersOp class: int currJumper, which is initialized to null.

After a piece successfully jumps within the makeMove() method, the makeMove() method must call hasNextJump(int jumper), where jumper is the new coordinates of the piece that just jumped.

If there is no next jump, then the turn switches to the other player, and currJumper is set to null. 

If there is a next jump, then two things have to happen. First, the turn stays with the current player. Secondly, currJumper is assigned the coordinates of the piece that just jumped.

Then, finally, that currJumper needs to be caught on the next move. This necessitates modifying near the start of the checkValidMove() method, and at the end of the checkValidMove() method. 
At the start -- fifth line, right after getting coordinates -- we must check if currJumper != null. If there is a currJumper, the player CAN ONLY move that piece. So if currJumper != null, we have to verify that the piece the player is moving is actually the currJumper; if it's not the currJumper, we return invalid move. If it is the currJumper, we proceed as usual.
Then, at the end of the checkValidMove() method, we have to make sure that if there is a currJumper, it JUMPED on this move, and did not just take a free move. Thus, if the method would have returned 1 (a normal move), but there is a currJumper != null, then we must return false -- attempting to use a jumper's second move to only move one-space is illegal.

This should be thoroughly doable, and it seems to be the only way to accurately monitor legal jumping chains. It will also ensure that all thinking is done in CheckersOp. Cheers! I think you can reply on this comment if there are questions.

**Comment by aivantg** [comment]
I'll take care of it hopefully tonight or Sunday morning
